filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/srm-grid002domain-ext-unix.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: '${ES_USERNAME:elastic}'
  password: '${ES_PASSWORD:changeme}'
  #Descomentar la siguiente línea descomentada para que ejecute la pipeline
  #pipeline: logs-pipeline

xpack.monitoring.enabled: true
logging.to_files: false

setup:
  dashboards.enabled: false
  template.overwrite: false
  template.settings.index.number_of_shards: 1
  template.settings.index.number_of_replicas: 0
